---
# tasks file for prometheus-role


- name: Update packages
  yum:
    name: '*'
    state: latest

- name: Install python3
  yum:
    name: python3
    state: present

- name: Install python3-pip
  yum:
    name: python3-pip
    state: present
      
- name: Pull tar repo from github
  ansible.builtin.unarchive:
    src: "{ github_project_url }"
    dest: /opt
    remote_src: yes

- name: Install python requirement
  ansible.builtin.pip:
    requirements: "{ requirements_path }"
      
- name: Move Prometheus unit file
  command: "mv { unitfile_path } /lib/systemd/system/prometheus.service"

- name: Start prometheus
  service:
    name: prometheus.service
    state: started
    enabled: yes
